version: '3.6'

services:
  wsf-bot:
    build: .
    image: wsf-bot:local
    container_name: wsf-bot
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./config.yml:/usr/bot/config.yml